version: '3'

services:
  keycloak:
    image: keycloak-srv
    hostname: keycloak-srv
    ports:
      - "9090:8080"
    build: .
    depends_on:
      - db

  db:
    image: keycloak-db
    hostname: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password