version: '3'

services:
  keycloak:
    image: keycloak-srv
    hostname: keycloak-srv
    ports:
      - "9090:8080"
    build: .
    depends_on:
      - db
    networks:
        - keycloak-network

  db:
    image: keycloak-db
    hostname: keycloak-db
    volumes:
      - keycloak-db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:

volumes:
  keycloak-db_data: