# Utilisation de l'image de base PostgreSQL
FROM postgres:latest

# Variables d'environnement pour la base de données PostgreSQL
ENV POSTGRES_DB=keycloak
ENV POSTGRES_USER=keycloak
ENV POSTGRES_PASSWORD=password
